TARGET=sonalyze
SUBDIRS=application \
	cmd cmd/add cmd/cards cmd/clusters cmd/configs cmd/gpus cmd/jobs cmd/load cmd/metadata \
	cmd/nodes cmd/parse cmd/profile cmd/report cmd/sacct cmd/snodes cmd/sparts cmd/top \
	cmd/uptime \
	common \
	daemon \
	data/card data/common data/cpusample data/gpusample data/node data/sample \
	data/samplejob data/slurmjob data/slurmnode data/slurmpart \
	db db/errs db/filedb db/parse db/repr db/special \
	table

include ../go-rules.mk
