name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Test
      run: |
        make test
        make regress

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate .yarnrc.yml using default GITHUB_TOKEN
      working-directory: 'code/dashboard-2'
      run: |
        echo 'nodeLinker: node-modules' > .yarnrc.yml
        echo 'npmScopes:' >> .yarnrc.yml
        echo '  naicno:' >> .yarnrc.yml
        echo '    npmRegistryServer: "https://npm.pkg.github.com"' >> .yarnrc.yml
        echo 'npmRegistries:' >> .yarnrc.yml
        echo '  "//npm.pkg.github.com":' >> .yarnrc.yml
        echo "    npmAuthToken: \"${{ secrets.GITHUB_TOKEN }}\"" >> .yarnrc.yml  

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'code/dashboard-2/yarn.lock'

    - name: Install dependencies
      working-directory: 'code/dashboard-2'
      run: yarn install --immutable

    - name: Run tests
      working-directory: 'code/dashboard-2'
      run: yarn test
